### ISSUE TITLE
Can SNI be disabled on a client or ignored on the server?

### ISSUE THREAD

**Issue by bvinc** [ctz/rustls#123]
I'm currently experimenting with TLS on other protocols besides HTTP, so I have no use for SNI.  Imagine that I'm using no name-based virtual hosting of any kind and can just work with IP addresses.

Currently, on the client side, rustls appears to always take in a hostname string and use it in the SNI extension in the handshake.

Currently, on the server side, if it receives the SNI extension, then it verifies that the certificate used matches the SNI hostname that the client gave, or else gives the error "The server certificate is not valid for the given SNI name".

Both behaviors combined means that I have to invent a string on the client side, and complicate the certificates used on the server side.

Ideally, I want one of the following:
1.  To be able to disable SNI in the client.
2.  To be able to ignore/disable SNI in the server, since it's just a suggestion.

Would you be interested in either of these two features if I made a PR?  If so, what would the API look like?  Would they be "dangerous"?

Relevant section of RFC 6066:
```
   It is RECOMMENDED that clients include an extension of type
   "server_name" in the client hello whenever they locate a server by a
   supported name type.

   A server that receives a client hello containing the "server_name"
   extension MAY use the information contained in the extension to guide
   its selection of an appropriate certificate to return to the client,
   and/or other aspects of security policy.  In this event, the server
   SHALL include an extension of type "server_name" in the (extended)
   server hello.  The "extension_data" field of this extension SHALL be
   empty.
```

**Comment by bvinc** [comment]
The more I think about this, the more I think #2 is the right solution.

I think I should be able to call ServerConfig::set_single_cert(...) and be able to serve a certificate, even if it doesn't match the SNI name that the client gave me.  The error `The server certificate is not valid for the given SNI name` is just a sanity check that isn't valid for all use cases.  It should be perfectly safe to delete or to be able to disable, this error.

**Comment by briansmith** [comment]
> Imagine that I'm using no name-based virtual hosting of any kind and can just work with IP addresses.

Rustls can't support that scenerio because it doesn't support connecting to a server that doesn't have a domain name. This is made clearer in the current master branch, where the hostname input is a `DNSName` instead of a `&str`.

Adding support for IP addresses is a lot of work. It requires, in particular, adding IP address support to the webpki certificate validation library. And it requires that the CA actually issue certificates for IP addresses and that the CA actually encodes the IP addresses as IpAddress subjectAltName entries.

> To be able to disable SNI in the client

Having a feature to disable SNI in the client is definitely a reasonable thing to do for a variety of reasons. If that solves your problem then I recommend implementing that. However, you'd still need an actual  DNS name to connect unless/until IP address support is added (see above), and the client would still validate the server certificate against that DNS name.

> To be able to ignore/disable SNI in the server, since it's just a suggestion.

I would say that it is bad, in general, to ignore the SNI if SNI is given.

**Comment by bvinc** [comment]
I just want to explain my use case a little better.  Imagine you're developing your own protocol, and you want it to be encrypted.  Imagine SSH didn't exist, and you're developing it.  TLS gives you all of the tools you need and seems like a good choice.  You wouldn't care what certificates CAs were issuing, because you would decide yourself what certs to trust.  You would definitely want people to be able to connect by IP address and you wouldn't want people to need new certificates every time they added a new IP address or domain name.  In this hypothetical protocol, just like SSH, they're intending to connect to the machine, not the name.  TLS, at it's most basic, should be able to support this perfectly, right?

> Rustls can't support that scenerio because it doesn't support connecting to a server that doesn't have a domain name.

Maybe this is all that needs to be said.  I need to be able to connect to IP addresses.  I could put in a fake DNS name and then override the client-side verification to ignore the fake DNS name.  Only that wouldn't work, because I want the IP when verifying.  I would have to encode the IP address into a DNS name first and then decode it.  I would be really fighting the API at that point.

This change alone really makes it less of a generic TLS library and more of an HTTPS library.

> Having a feature to disable SNI in the client is definitely a reasonable thing to do for a variety of reasons. If that solves your problem then I recommend implementing that.

It would... only because disabling SNI on the client side ends up removing the SNI sanity check on the server side that's causing me problems.

But this really isn't ideal.  If a client ever sent my protocol an SNI name, my server would just puke with an error.

>  I would say that it is bad, in general, to ignore the SNI if SNI is given.

It's indicative of a mistake in the modern world of HTTPS, because you're almost certainly just giving a certificate to a client that's going to immediately deny it.  But legally, this is a perfectly valid thing to do, right?  Before SNI, this is what every server did.

TLS was designed to generically encrypt any connection, even without SNI.  The RFC recommends the client always send SNI, because it can't hurt and the server can always choose to ignore it.

So... I hope I don't sound argumentative, but does rustls aim to be a generic TLS library, or more of a simple modern HTTPS library?  Maybe my use case is better suited for a library like OpenSSL.  That isn't necessarily a bad thing.

**Comment by briansmith** [comment]
> I just want to explain my use case a little better. Imagine you're developing your own protocol, and you want it to be encrypted. Imagine SSH didn't exist, and you're developing it.

That sounds like an awesome project. In fact, I've been kicking around exactly that idea for a while.

> You wouldn't care what certificates CAs were issuing, because you would decide yourself what certs to trust.

Rustls already lets you do this, by plugging in your own certificate verification.

> You would definitely want people to be able to connect by IP address and you wouldn't want people to need new certificates every time they added a new IP address or domain name.

In order to support that, someone would have to write a PR to support connecting by IP address w/o a DNS name, since right now Rustls requires the hostname it is given to be a DNS name.

> I could put in a fake DNS name and then override the client-side verification to ignore the fake DNS name. ... Only that wouldn't work, because I want the IP when verifying. I would have to encode the IP address into a DNS name first and then decode it. I would be really fighting the API at that point.

That might work in the current release on crates.io, but it wouldn't work in the current master branch on GitHub, because now Rustls verifies that the name it is given is actually a valid DNS name, as part of a bug fix for SNI handling.

> This change alone really makes it less of a generic TLS library and more of an HTTPS library.

Only supporting DNS names is pretty reasonable for the vast majority of uses of HTTPS, IMAP over TLS, SMTP over TLS, and most other uses of TLS.

In the future, I'd like to add support for SRVNames too. I would guess @ctz would accept a PR from me that adds SRVName support.

It seems like you'd like to add IP address support too. I'd ask @ctz if he'd accept a PR that accepts IP address support. In other words, let's clarify whether the lack of IP address support is an intentional long-term goal, or whether it is a short-term limitation.
 
> But this really isn't ideal. If a client ever sent my protocol an SNI name, my server would just puke with an error.

That would be the right thing to do, IMO. If the client isn't actually identifying your server by DNS name, then it shouldn't send an SNI with a DNS name.

> It's indicative of a mistake in the modern world of HTTPS, because you're almost certainly just giving a certificate to a client that's going to immediately deny it. But legally, this is a perfectly valid thing to do, right? Before SNI, this is what every server did.

Of course it's reasonable to ignore a feature that you didn't know about when you wrote the code. But, once we know about it, it makes sense to support it as well as we can.

> TLS was designed to generically encrypt any connection, even without SNI. The RFC recommends the client always send SNI, because it can't hurt and the server can always choose to ignore it.

The client needs to send the SNI information that is relevant for its certificate validation. If there is no such information then it shouldn't send an SNI. If it validates by IP address then it needs to send an IP address in SNI. However, there's no standard to put the IP address in SNI, so the next best thing that it can do is to just not send SNI. It's never correct to send SNI with an IP address encoded as a DNS name. It's not correct to send SNI with a DNS name that isn't relevant to the client's needs.

> So... I hope I don't sound argumentative, but does rustls aim to be a generic TLS library, or more of a simple modern HTTPS library?

I think Rustls intends to be general-purpose. Again, let's distinguish between a short-term limitation of the API and long-term design goals. Just because a feature isn't supported now doesn't mean it won't ever be supported.

**Comment by bvinc** [comment]
> That sounds like an awesome project. In fact, I've been kicking around exactly that idea for a while.

That's actually not my project, but I also think it sounds awesome.  I just think it's a great example of a protocol where you would want to connect to a machine, and not a name, and client-side verification of a server certificate will probably just look like: "Is this the certificate that I expected?"

I'm not sure if I was thinking about this clearly before.  So, rustls lets you start a TLS session on anything that can be read/written to.  Starting a TLS session on a connection to an IP address is no problem at all.

The 2nd argument to ClientSession::new is only used in 2 cases: 1.  The client SNI extension sent during the handshake,  2.  The verification of the server's certificate for comparing with the DNS names in the certificate.  Those are the only 2 cases, right?  Both of these cases are "typed" as DNS names (in SNI, and in certificates).  It _does_ make perfect sense that the rust API forces that the argument is a DNS name.  I don't really need it to support IP addresses.  The only weird thing is that if I disable SNI on the client and then override the verification function, it's possible that 2nd argument in ClientSession::new never gets used.

I think there is only one place where we may disagree.  It's that I think it's perfect reasonable to have a TLS server that *always* uses the same certificate information, no matter what SNI name the client gives.  I view SNI as something that _enables_ the server to pick a different certificate.  I think it's analogous to the Host: header on HTTP allowing name-based hosting, but IP-based hosting still exists and is a valid thing to do.  It's also valid to have a certificate without a sub_alt_name field extension, right?  I really want to be able to opt out of the server-side checking that the sub_alt_name matches the client's SNI.  Another reason I find it surprising is that this function exists:

```rust
set_single_cert(&mut self, cert_chain: Vec<Certificate>, key_der: PrivateKey)

Sets a single certificate chain and matching private key. This certificate and key is used for all subsequent connections, irrespective of things like SNI hostname.
```
Yet trying to use the function just like the documentation says results in an error.

Thanks for putting up with me and responding to me.  So currently, I think there are only 2 changes I want and I'm willing to submit:

1.  Be able to disable client SNI on the client side.
2.  Remove or be able to opt out of the server-side certificate sub_alt_name SNI sanity check.

I realize that #2 is a bad idea for anyone using HTTPS, but is there any reason why it should generally be disallowed?  You see why it would be useful to disable for a general session encryption like a TLS version of SSH, right?

**Comment by bvinc** [comment]
I'm going to close this issue because it's all over the place and I'll submit a PR for the changes I think should go in.

**Comment by doroved** [comment]
**Disabling Server Name Verification in Rustls (Version 0.23.19)**
https://github.com/rustls/rustls/issues/578#issuecomment-2525276839
