### ISSUE TITLE
Ignore SNI values entirely when using set_single_cert

### ISSUE THREAD

**Issue by matthauck** [ctz/rustls#130]
It was a surprise to me when using `set_single_cert` when the rustls refused to handshake when the client-presented SNI did not match a subjectAltName in my certificate. It seem better to me to allow the client to decide to refuse to handshake than have a server that refuses to even present its server certificate if SNI does not match, in particular when `set_single_cert` is used for the `ServerConfig`.

**Comment by sanmai-NL** [comment]
I wonder what the security implications are of such a change in design. One thing is clear though, I also had trouble debugging thsi simple issue (#129), and @P-E-Meunier too (#127), all in recent days. @ctz may want to address the challenge library consumers appear to have here. I'm personally looking into whether the docs can be improved.

**Comment by matthauck** [comment]
The design decision here essentially is whether the server has the responsibility (or right?) to make this decision on behalf of the client or not. 

In my opinion:
- The job of the server is to tell the client its identity
- The job of the client is to decide whether to trust the server's identity

Refusing to even `Server Hello` because the SNI doesn't match prevents the client from making this decision, presumably trying to take the high ground since so many clients out there don't validate certs? 

I think that doing this choice only for `set_single_cert` makes sense since that `ServerConfig` is not asking the library to choose from a set of identities based on SNI, it just has a single identity and should always return it. 

I think this is in line with the RFC:

> It is NOT RECOMMENDED to send a warning-level unrecognized_name(112) alert,
because the client's behavior in response to warning-level alerts is
unpredictable.  If there is a mismatch between the server name used
by the client application and the server name of the credential
chosen by the server, this mismatch will become apparent when the
client application performs the server endpoint identification, at
which point the client application will have to decide whether to
proceed with the communication.

(https://tools.ietf.org/html/rfc6066#section-3)

(Another minor point here from re-reading this is that `unrecognized_name` alert is probably preferable to InternalError)

**Comment by ctz** [comment]
> Refusing to even Server Hello because the SNI doesn't match prevents the client from making this decision, presumably trying to take the high ground since so many clients out there don't validate certs?

It's more to make a server misconfiguration more obvious to the server admin.  Now, failing during a handshake is not an ideal time, but is also somewhat unavoidable given it uses the SNI value the client sends.

I wonder if this arrangement would be better, though:

1. keep `server::ResolvesServerCert` as is (a low-level trait for totally reconfiguring certificate selection logic); make the main library not second-guess or check the results.
2. add, and test, and recommend, an implementation of `server::ResolvesServerCert` which does SNI certificate switching. This is an improvement because it can check the certificates agree with their registered names earlier, and be useful and vocal about problems.
3. make the thing that underlies `set_single_cert` entirely ignore SNI, as the commentary there actually already says.

For (2), this would be just a small struct that probably wraps a `collections::HashMap<webpki::DNSName, sign::CertifiedKey>`, and checks the names and certificates agree at start-up time using the existing `CertifiedKey::cross_check_end_entity_cert` function.

**Comment by P-E-Meunier** [comment]
Hi! I'm no TLS expert, but does this handle my use case (#127), where the server has no DNS name, and is accessed directly by its IP?

**Comment by matthauck** [comment]
That sounds like a great plan to me. 👍

**Comment by briansmith** [comment]
@ctz I think your suggested plan of action is reasonable.

I will clarify why the check was added. We save the SNI in the (TLS 1.2) session structure for session resumption; i.e. we bind the SNI name to the session master secret. How is this binding justified? In the case of a custom certificate resolver, the resolver might not have looked at the SNI value at all—in fact, that seems to be exactly the intended semantics of `set_single_cert`. If nothing actually looked at the SNI value then does it really make sense to bind the SNI name to the session? I think that's very questionable, and that's why I added the check. Note in particular that the check was added in the PR that added the SNI to the session state.

Ideally, we would have a way to differentiate "The certificate isn't valid for the SNI and I know that and I still want to continue" from "I accidentally chose the wrong certificate." The current server cert resolver API doesn't have a way for the resolver to indicate this, which is why I conservatively assumed the worst.

In particular, consider the case where you have a wildcard certificate for *.user-generated-content.example.com with a weakly-protected private key and you have a certificate for login.example.com with a highly secured private key. Assume somebody stole the private key for *.user-generated-content.example.com. If they can somehow trick the server into using the certificate for *.user-generated-content.example.com for a connection to login.example.com then can they somehow gain a significant security advantage? Probably not, but I'm not 100% convinced.

Also, in the bug reports that Rustls received so far, people are blaming this check for problems that are really different issues:

1. Rustls (e.g. it doesn't yet have a clear way to work with systems that aren't using traditional web PKI certificate validation using DNS names for authentication). I'd rather just have this general issue addressed, either as WONTFIX, or by seeing a proper proposal for some alternative authentication mechanisms.

2. Bad practice on the user's part, e.g. using the subject CN instead of subjectAltName/dNSName. I think something that's been implicit in the design of Rustls from the start is that Rustls prefers to avoid workarounds for issues that could and should be fixed internally, like this. In other words, fix what's broken, instead of adding junk logic (IMO) to Rustls just to work around it.

That said, I do think there are valid reasons to not have the server's certificate be valid for the SNI, however I think those use cases are advanced. This is why I think the current default behavior is a reasonable and good default, and advanced users should have to opt into disabling the check; i.e. using `set_single_cert` by itself shouldn't disable this check.

**Comment by briansmith** [comment]
> Refusing to even Server Hello because the SNI doesn't match prevents the client from making this decision, presumably trying to take the high ground since so many clients out there don't validate certs?

This isn't why the check was added. It's not about babysitting clients that do the wrong thing. It's truly to minimize risks associated with using the wrong certificate and key pair. I would love to see a proof that the check isn't necessary and never helps improve security. Right now I don't have such a proof.

**Comment by matthauck** [comment]
Thanks for the explanation. I was guessing in the dark as to why the check was there. :) Binding session resumption to the SNI name definitely does raise the stakes for getting it right in the case that there are multiple certificates/identities in play. 

Totally on board with having secure defaults. I love that I don't have to configure rustls a to to make it secure. Totally for it. I think fewer issues would have been filed if the messaging/logging about why the handshake was failing was clearer.

(Most people will probably run into this in testing and not in production -- openssl command line is such a pain to issue self-signed certificates with a subjectAltName)

**Comment by ctz** [comment]
The resolution discussed here has been implemented in f22c9ba.
