### ISSUE TITLE
Is it possible to use pkcs12 for client authentication?

### ISSUE THREAD

**Issue by opensourcegeek** [ctz/rustls#150]
I'm looking to use JKS keystore with rust lang, I can export certs/key to P12 format. However I'm not sure how to use that with setting up ClientConfig. I tried using the P12 format with native-tls and it works.

I tried extracting cert/key in PEM format and feeding it to examples/tlsclient but it did not work

```
thread 'main' panicked at 'assertion failed: keys.len() == 1', examples/tlsclient.rs:383:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

```
Any ideas please?

**Comment by ctz** [comment]
This is likely to be something that the webpki and ring crates would need to expose, rather than rustls.

Personally I think PKCS#12 is a pretty poor standard -- it's enormously complex for the facilities which it provides. I'd suggest converting your keys/certs externally before providing them to rustls.

**Comment by opensourcegeek** [comment]
Ok, thanks - currently I'm using native-tls so I'll leave it for now.
