### ISSUE TITLE
Implement support for QUIC

### ISSUE THREAD

**Issue by djc** [ctz/rustls#161]
I have started work on a pure-Rust implemenation of the QUIC protocol (current draft). I would like to use `rustls` for all TLS-related stuff. Are you interested in having that support implemented? QUIC currently specifies TLS 1.3 only, but there are some extensions that are needed. In particular, so far I've noticed the `TransportParameters` extension as described [in the draft spec](https://tools.ietf.org/html/draft-ietf-quic-transport-10#section-7.4). I can work on this, but would appreciate your support/guidance where necessary.

**Comment by ctz** [comment]
Neat. Yes.

Perhaps we could have traits for client and server starting like:

```
mod quic {
pub trait QuicClient {
  fn get_transport_params(&self) -> msgs::quic::ClientTransportParameters;
  fn process_server_transport_params(&self, params: &msgs::quic::ServerTransportParameters) -> Result<(), TLSError>;
}

pub trait QuicServer {
  fn process_client_transport_params(&self, params: &msgs::quic::ClientTransportParameters) -> Result<msgs::quic::ServerTransportParameters, TLSError>;
}
}
```

... then extended as required for stuff like the Cookie extension (which AIUI is how source address ownership is established, and how stateless retries work).

These `msgs::quic` types can be plumbed into the existing `msgs::handshake::ClientExtension` etc types, but we can keep `TransportParameterId` opaque as a `u16`? There's no need for rustls to track that enum.

It probably makes most sense for these trait impls to be per-session (rather than per-ClientConfig/ServerConfig) which should make it easiest to keep the right context around to fulfil these calls. That will mean we'll need extra QUIC-specific ClientSession/ServerSession constructor-like functions.

All this can go under a `quic` feature, as most users won't benefit from the extra API surface.

**Comment by ctz** [comment]
Related, see #151

**Comment by djc** [comment]
Sounds good so far. I've submitted #162 for the basic handling of `TransportParameters`.

What do you think is the best way to plug into the handshake infrastructure? For example, I don't think we'd want to duplicate most of the stuff in `emit_client_hello_for_retry()`, but I'm not sure to what degree the QUIC side will differ.

**Comment by Ralith** [comment]
I'm also working on [a QUIC implementation](https://github.com/Ralith/quicr) (perhaps me and @djc can combine efforts?), currently using OpenSSL largely due to #151. My implementation is successfully completing the cryptographic handshake.

Above all else, rustls does *not* need strictly QUIC-specific features for it to be usable in a QUIC implementation. OpenSSL manages to expose a sufficiently extensible API to be usable for a QUIC implementation without specific support, and rust makes that sort of thing far easier. Taking a similar approach would improve maintainability, limit exposure to the still-unstable QUIC draft specification, and obviate the need for a feature gate.

I believe the minimum necessary API features that aren't trivially present are as follows:
- Support for injecting and processing custom extensions. See [the OpenSSL implementation](https://www.openssl.org/docs/manmaster/man3/SSL_CTX_add_custom_ext.html). This is unnecessary given #162, but is a more general solution and may be useful elsewhere.
- Support for stateless handshakes. See [the OpenSSL implementation](https://www.openssl.org/docs/manmaster/man3/SSL_stateless.html). As in OpenSSL, this API can be very simple; we only need to know whether a `HelloRetryRequest` was written out or an error occurred, and the existing handshake machinery can otherwise be reused. An interface to generate and validate cookies for said HRR is also needed.
- Accessors for the negotiated handshake digest and symmetric ciphers after the handshake completes, such that they can then be used on their own. See [the OpenSSL implementation](https://www.openssl.org/docs/man1.1.1/man3/SSL_CIPHER_get_handshake_digest.html) (also [here](https://www.openssl.org/docs/man1.1.0/ssl/SSL_CIPHER_get_cipher_nid.html)). This is used for the actual encryption of QUIC packets; QUIC makes no use of regular TLS framing. Ideally this API would directly expose the underlying ring vocabulary so the QUIC implementation needn't maintain a fragile mapping between TLS and ring notions by hand, just as the OpenSSL implementation exposes handles/identifiers that can be passed directly to its lower-level `EVP` crypto interfaces.

I'm fairly sure the TLS communications within a QUIC cryptographic handshake are perfectly valid for a regular TLS session, so there should be no need for QUIC-specific code in the meat of rustls. QUIC treats TLS as a black box to the greatest extent possible, so mostly an implementation on top of rustls will just be shuffling data through `read_tls`/`write_tls` and checking the error and completeness flags. Aside from supporting stateless handshakes at all, I expect the necessary changes will be noninvasive.

**Comment by djc** [comment]
What I had in mind (which I think matches what @ctz was thinking -- but I could be wrong!) was that rustls should not be in the business of exposing APIs for a TLS toolbox, but instead provide a high-level API to serve the high-level use cases. This provides greater flexibility for rustls, and also better security: because rustls changes are needed for low-level TLS tweaks, there is additional review/scrutiny.

I don't yet fully grasp whether rustls will need to provide QUIC-specific API, but if it does then it might make more sense to make that explicit instead of providing lower-level API.

**Comment by Ralith** [comment]
The above are not particularly low-level APIs, nor do I see any reason to deem them security hazards. I also think there is considerable value in allowing the rustls maintainers to focus on TLS features and conformance rather than a bunch of unstable QUIC implementation details.

**Comment by Ralith** [comment]
Upcoming QUIC changes will drastically change the interface required to the TLS implementation. In particular, future revisions of QUIC will process raw, unencrypted TLS messages directly, rather than merely providing a reliable transport stream for otherwise TCP-style communications.

See https://github.com/quicwg/base-drafts/pull/1377 for details.

**Comment by djc** [comment]
(See #187.)

**Comment by djc** [comment]
We can probably close this now?

**Comment by ctz** [comment]
Yeah 👍 Raises new issues/PRs for further work here
