### ISSUE TITLE
`rsa_private_keys` accepts PKCS8 file

### ISSUE THREAD

**Issue by sanmai-NL** [ctz/rustls#173]
It returns an `Ok` `Result` with an empty list of keys, rather than an `Err` result due to the mismatched format.
See https://docs.rs/rustls/0.12.0/rustls/internal/pemfile/fn.rsa_private_keys.html.

**Comment by raskad** [comment]
I just had a look at this.
See this file: https://github.com/ctz/rustls/blob/master/src/pemfile.rs
The problem seems to be, that the `extract` function is always returning `Ok`. This function is called by `certs`, `rsa_private_keys` and `pkcs8_private_keys`. If no valid cert or key is found, the return value will be `Ok([])` like @sanmai-NL described.

This could be prevented by checking if the returned Vec is empty and returning `Err(())` in that case. The type `()` is obviously not great, but returning an error type would mean changing the public interfaces of `certs`, `rsa_private_keys` and `pkcs8_private_keys`.

@ctz what do you think about this?

**Comment by mocsy** [comment]
Today a pikachu ( IDK how to pronounce pkcs8) key invaded my rsa keys resulting in` thread 'main' panicked at 'assertion failed: index < len', src/liballoc/vec.rs:894:9`
This issue helped me to figure it out, adding this comment for other potential googlers.

**Comment by briansmith** [comment]
I think that wherever a non-PKCS#8 key is accepted, a PKCS#8-formatted key should be accepted to. There is basically zero risk of accidentally interpreting a non-PKCS#8 file as a PKCS#8 file because of the extensive checking that *ring* does underneath.

**Comment by therealchaudhri** [comment]
Any update on this? It still errors when adding PKCS#8-formatted key.

For reference I've been receiving the error 
`thread 'main' panicked at 'removal index (is 0) should be < len (is 0)', src/liballoc/vec.rs:1057:13`

**Comment by marknijboer** [comment]
I had the same issue when I wanted to use a Let's Encrypt `privkey.pem`. A workaround I found is manually change it to RSA format: 
```bash
openssl rsa -in privkey.pem -out privkey-rsa.pem
```

Rustls has no issues with the resulting `privkey-rsa.pem`

**Comment by ctz** [comment]
Going to close this on the basis that https://crates.io/crates/rustls-pemfile now has preferable APIs (`read_all`) and contains the offending code.
