### ISSUE TITLE
Supported cipher suites (symmetric crypto algorithms) should be customizable

### ISSUE THREAD

**Issue by briansmith** [ctz/rustls#177]
In #176 I suggest a path forward for allowing the application to customize the signature part of cipher suite selection.

Along the same lines, it would good to allow the application to control which symmetric algorithms are used. For example, the application may want to enable only AES-GCM-256 or only ChaCha20 in order to minimize the amount of crypto code in its TCB.

I suggest that this be implemented by adding fields to the `ClientConfig` and `ServerConfig` that specify which (symmetric) cipher suites are allowed. Then when advertising/selecting cipher suites, the client/server should filter the list according to this setting. The default would be the current set of defaults.

**Comment by ctz** [comment]
If I understand your request correctly, this is already implemented:

- https://docs.rs/rustls/0.12.0/rustls/struct.ClientConfig.html#structfield.ciphersuites
- https://docs.rs/rustls/0.12.0/rustls/struct.ServerConfig.html#structfield.ciphersuites

**Comment by briansmith** [comment]
@ctz AFAICT not enough of the cipher suite internals are exposed to actually allow one to configure them in a meaningful way.

For example, I can't filter based on `bulk` because `BulkAlgorithm` isn't public. I shared PR #178 to fix this. This happens to address my specific use case for this issue.

**Comment by ctz** [comment]
I'm going to close this on the basis that it's now possible, even if it's not separate from ciphersuite customisation.

**Comment by MightyPork** [comment]
@ctz I just tried to add a custom SupportedCipherSuite and failed on `pub(crate) hkdf_algorithm: ring::hkdf::Algorithm,` in the struct. Since you closed this, could you show us an example how it's done?

We're trying to integrate a hardware device with the following requirements:

![Screenshot_20190830_104414](https://user-images.githubusercontent.com/2041118/64006988-a8e66780-cb13-11e9-9dc0-5f7d3965c022.png)

here's what I tried (it probably wouldn't have worked anyway, I'm not sure what some of the settings mean), but I can't try because it won't compile because of hkdf_algorithm. I tried cloning one of the existing suites in lazy_static, but they aren't exposed and also don't implement Clone.

```
pub static CUSTOM_SUITE: SupportedCipherSuite = SupportedCipherSuite {
    suite: CipherSuite::TLS_RSA_WITH_AES_256_CBC_SHA256,
    kx: KeyExchangeAlgorithm::BulkOnly,
    sign: SignatureAlgorithm::Anonymous,
    bulk: BulkAlgorithm::AES_256_GCM,
    hash: HashAlgorithm::SHA256,
    enc_key_len: 16,
    fixed_iv_len: 12,
    explicit_nonce_len: 0,
    hkdf_algorithm: ring::hkdf::HKDF_SHA256, // :(
};
```
i really wish I could avoid re-adding the openssl dependency...

**Comment by ctz** [comment]
`SupportedCipherSuite` is not a user-implementable struct. I'm afraid rustls does not support either RSA-encryption-style key exchange or any CBC-mode so will not talk to this device.

**Comment by ctz** [comment]
For your next steps I would investigate improving the configuration of the device. If that's not possible you may be stuck with openssl and a quite dated configuration.

**Comment by MightyPork** [comment]
Okay, thanks for the answer anyway. The device is new, but vendor locked and we have no control over it. I'm afraid there's many "IoT" devices that don't support latest cipher suites. Well, let's revert back to native-tls and its openssl version nightmares
