### ISSUE TITLE
Client sees is_handshaking()=false while wants_write=true and handshake is not done on Server

### ISSUE THREAD

**Issue by gorup** [ctz/rustls#250]
Hello!

It appears that a client session can believe that `is_handshaking()` is false (i.e. handshake is complete)  even though `wants_write()` is true, and from the server's perspective, the handshake is still in progress. 

I wrote a little program which shows that the client will believe handshaking is complete even though the server does not. Only after we poke the client again will it write the bytes needed for the server to feel the handshake is complete.

Tester program repo: https://github.com/gorup/rustls-handshake-test

This could be due to a bug in `complete_io`, or it could be to my understanding being incorrect. Specifically, I may not be adhering to the 'contract' of rustls by not calling `write_tls` when `wants_write()` is true, which is the case after the first `complete_io` call in my program, but that breaks my understanding of:
- `complete_io`: Should perform IO until handshake is complete (Technically this is the case?)
- `is_handshaking`: Should not be true for the client and not the server? <-- This may be an incorrect assumption?

Any guidance would be appreciated, thanks!

**Comment by ctz** [comment]
Thanks for the report. I think rustls is behaving as designed here. There are indeed window in a handshake where the client and server believe different things about whether the handshake is finished. Specifically, when the final flight of handshake messages are in flight.

TLS1.2:
- for a full handshake, the server will see `is_handshaking() -> false` before the client
- for an abbreviated handshake, the client will see `is_handshaking() -> false` before the server

TLS1.3:
- the client will see `is_handshaking() -> false` before the server (this is the case your test program observes), for all kinds of handshake

The other point here is that `is_handshaking()` only relates to rustls' internal protocol state, it does not take account of data which is waiting to be sent in rustls' buffers (because the buffers just store bytes and don't know what these bytes mean). I could totally see that this might be confusing though.
