### ISSUE TITLE
Can't run example with system certificate

### ISSUE THREAD

**Issue by vi** [ctz/rustls#26]
```
# RUST_BACKTRACE=1 /mnt/src/git/rustls/target/debug/examples/tlsserver --certs /etc/ssl/certs/ssl-cert-snakeoil.pem --key /etc/ssl/private/ssl-cert-snakeoil.key http
thread 'main' panicked at 'Invalid RSA private key: ()', ../src/libcore/result.rs:788
stack backtrace:
   1: 0x56943771 - std::sys::backtrace::tracing::imp::write::h482d45d91246faa2
   2: 0x56946bae - std::panicking::default_hook::_{{closure}}::h89158f66286b674e
   3: 0x56945879 - std::panicking::default_hook::h9e30d428ee3b0c43
   4: 0x56945f73 - std::panicking::rust_panic_with_hook::h2224f33fb7bf2f4c
   5: 0x56945dfd - std::panicking::begin_panic::hcb11a4dc6d779ae5
   6: 0x56945d0e - std::panicking::begin_panic_fmt::h310416c62f3935b3
   7: 0x56945c6e - rust_begin_unwind
   8: 0x5697ed04 - core::panicking::panic_fmt::hc5789f4e80194729
   9: 0x566603eb - core::result::unwrap_failed::h758c322be2590739
                at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/result.rs:29
  10: 0x5664ffab - _<core..result..Result<T, E>>::expect::h5c4ab8a24731780f
                at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/result.rs:750
  11: 0x566ca298 - rustls::server::AlwaysResolvesChain::new_rsa::h7532f7f3b684f42d
                at /mnt/src/git/rustls/src/server.rs:166
  12: 0x566cacfd - rustls::server::ServerConfig::set_single_cert::he44ef2078618689f
                at /mnt/src/git/rustls/src/server.rs:215
  13: 0x565fe1ae - tlsserver::make_config::h278ad6ef743ab7d9
                at /mnt/src/git/rustls/examples/tlsserver.rs:447
  14: 0x565fe95b - tlsserver::main::h418b28d9f946c5ad
                at /mnt/src/git/rustls/examples/tlsserver.rs:485
  15: 0x56945bb5 - std::panicking::try::do_call::h9d5ad283de22edbd
  16: 0x5694e307 - __rust_maybe_catch_panic
  17: 0x56945098 - std::rt::lang_start::h352a66f5026f54bd
  18: 0x5660383a - main
  19: 0xf7582722 - __libc_start_main
  20: 0x565bdbb0 - <unknown>
```

Command line from README with pre-supplied certificate works although.

`ssl-cert-snakeoil.key` also begins with `-----BEGIN RSA PRIVATE KEY-----` like `test-ca/rsa/end.rsa`. I suppose the error message should tell what is exactly wrong.

`socat openssl-listen:8443,cert=/etc/ssl/certs/ssl-cert-snakeoil.pem,verify=0,key=/etc/ssl/private/ssl-cert-snakeoil.key -` does work.

**Comment by ctz** [comment]
Could you create another key that exhibits this problem and upload it?

**Comment by ctz** [comment]
Actually, nevermind. I realise now that ssl-cert-snakeoil.* are generated by the `ssl-cert` debian package. I installed that (on debian testing) and got a 2048-bit RSA key in `ssl-cert-snakeoil.key`, in a PKCS8 file. Converting it with openssl gave me a key I can use with rustls.

I'm guessing you have an older debian which makes a 1024-bit key. Could you confirm that? `openssl rsa -text -in /etc/ssl/private/ssl-cert-snakeoil.key | grep bit` should do the trick.

If so I agree that the error reporting when rejecting short RSA keys should be improved!

**Comment by vi** [comment]
`Private-Key: (1024 bit)`

Yes, I think it should discriminate invalid and insecure keys. Maybe it should even contain the list of legacy algorithm names just to output better error messages.

**Comment by radix** [comment]
I have been looking into ways to improve the error-reporting here, but I'm not really sure what to do yet (I haven't looked super thoroughly, but I've at least learned some things).

My impression now is that rustls can't give more specific information in the error because the `ring` library doesn't provide it. That could perhaps be rectified in the `ring` library by making `ring::signature::RSAKeyPair::from_der` return more information in an error.

Perhaps the best solution for now is to just add some helpful information to the error message, so that in addition to "Invalid RSA private key", we could add ": this may be because the key is using insecure algorithms or is too short".

Any thoughts @ctz?

**Comment by briansmith** [comment]
I believe https://github.com/briansmith/ring/issues/401 and https://github.com/briansmith/ring/pull/384 will provide the foundation for us to provide some more detailed error reporting in *ring*.

**Comment by berlincount** [comment]
I seem to have run into something similar - when generating a key/cert pair for (essentially)

`https://github.com/actix/examples/tree/master/rustls` via `openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -sha256 -nodes --subj '/CN=localhost/'`

this will barf per

`thread 'main' panicked at 'assertion failed: index < len', src/liballoc/vec.rs:993:9`

tracing back to the line

`config.set_single_cert(cert_chain, keys.remove(0)).unwrap();`

in the application code. if I unwrap the key from its structure per

`mv key.pem key-x.pem && openssl rsa -in key-x.pem -out key.pem`

it works just fine.

Seems like `rsa_private_keys` vs. `pkcs8_private_keys` just let this problem just run into a wall instead of handling it.

**Comment by brandonros** [comment]
It isn't clear. Are 1024-bit RSA private keys allowed?

**Comment by jbg** [comment]
> It isn't clear. Are 1024-bit RSA private keys allowed?

no

**Comment by ctz** [comment]
I believe this (specifically, good errors when rejecting 1024-bit keys) has been addressed upstream.
