### ISSUE TITLE
A way of choosing default hostname?

### ISSUE THREAD

**Issue by tuboythers** [ctz/rustls#335]
Hi, I was looking through the docs, but could not really see a way of doing this, not obvious at least. Is there a away for `rustls` to choose a default certificate for when the hostname does not match any record inside a SNI `cert_resolver`?

My code is pretty much like this:
```
let mut config = ServerConfig::new(NoClientAuth::new());
... load private key
... load cert
... create `CertifiedKey`
let mut sni_resolver = ResolvesServerCertUsingSNI::new();
sni_resolver.add("localhost.com", ..);
```

And this generally works, when I connect via HTTPS to localhost.com on my computer it loads up the certificate and the connection is secure. But there are a few issues which I am not quite sure how to go around by:

1. When you access using the WWW. hostname I get an error which states:

Sending fatal alert AccessDenied
unexpected error: General("no server certificate chain resolved")

and 2. If I tried to access with any other domain which is not in the `cert_resolver` I am getting the very same error from above. Example would be: `https://exampledomain.com`.

So my asking is whether this behaviour can be disabled. For point 1, the common name of the certificate is localhost.com and SANs: localhost.com, www.localhost.com, shouldn't that work out of the box instead of adding new `CertifiedKey`? 

And for point 2, I pretty much am aiming at receiving a privacy error here with a default server certificate. Say I have 2 certificates added, one for the server hostname, one for the domain which I am trying to access. If I try to access with another domain, which doesn't have configuration within rustls, I would like the server hostname (the first defined SSL) to be applied and get a Privacy Error in the browser as if the certificate is not matching the requested hostname.

Would you mind letting me know how to handle this efficiently?

**Comment by Darkspirit** [comment]
1) Common Name is disregarded, only SNI matters. At the moment, you need to call `sni_resolver.add()` for every SNI name. You could abstract it like nginx to have multiple SNI names per webserver vhost. If you want to create local certificates - even of domains you do not control - you could use https://github.com/FiloSottile/mkcert or XCA.
```
let mut sni_resolver = rustls::ResolvesServerCertUsingSNI::new();
let example_com = rustls::sign::CertifiedKey::new(load_certs("example.com.crt")?, load_key("example.com.pk8")?);
sni_resolver.add("example.com", example_com.clone()).unwrap();
sni_resolver.add("www.example.com", example_com).unwrap();
```

2) Instead, please consider going the other direction by using [HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) and [preloading](https://hstspreload.org/), so that your users automatically use https and won't be able to override certificate errors: We should work towards making an example on restarting a tokio-rustls + hyper server gracefully (after obtaining a new certificate).

**Comment by ctz** [comment]
I achieve this goal I would suggest you write your own `ResolvesServerCert` which wraps `ResolvesServerCertUsingSNI` but returns a default for unhandled SNI names.

**Comment by tuboythers** [comment]
@ctz actually your comment is quite legit. That's how I approached it and it is now working. Of course, I had to patch the crate itself a little as it doesn't allow adding a certificate with another name, if the names do not match, but it's otherwise working great.

Thanks!
