### ISSUE TITLE
Integrating with PKCS11-engine?

### ISSUE THREAD

**Issue by amrx101** [ctz/rustls#341]
Is it possible to hook with a `PKCS11-engine` deployed separately on `HSM(Hardware security Module)?`

If so, what would the steps be?

**Comment by ctz** [comment]
See #315 for the current position on this. To answer your other question:

The main trait you would implement is `sign::SigningKey`[1]. The primary method here is `choose_scheme` where you're given a set of `SignatureScheme`s[2] the client says it supports and have to choose one or return None (this aborts the handshake). Once you've chosen one, you return an implementation of the `sign::Signer`[3] trait. In your case the `sign` method here would do `C_Sign` (or whatever), and return the resulting signature.

(Unfortunately this is currently designed for keys with low latency access, like in a PKCS#11 provider, Microsoft CryptoAPI, etc. so is blocking rather than asynchronous. It's a TODO to make these and other extension points async.)

Once you have these two pieces, configuring a server to use them will involve, briefly:

- packaging your `sign::SigningKey` with the matching certificate chain into a `sign::CertifiedKey`[4]
- making a `ResolvesServerCertUsingSNI`[5] and feeding in your `sign::CertifiedKey` for all SNI hostnames you want to use it for,
- setting that as your `ServerConfig`'s `cert_resolver`[6]

[1]: https://docs.rs/rustls/0.15.2/rustls/sign/trait.SigningKey.html
[2]: https://docs.rs/rustls/0.15.2/rustls/enum.SignatureScheme.html
[3]: https://docs.rs/rustls/0.15.2/rustls/sign/trait.Signer.html
[4]: https://docs.rs/rustls/0.15.2/rustls/sign/struct.CertifiedKey.html
[5]: https://docs.rs/rustls/0.15.2/rustls/struct.ResolvesServerCertUsingSNI.html
[6]: https://docs.rs/rustls/0.15.2/rustls/struct.ServerConfig.html#structfield.cert_resolver

**Comment by ctz** [comment]
If you do make a crate to do this, I'd love to know about it and link to it from here.

**Comment by amrx101** [comment]
@ctz , I hope commenting here is okay.

I am gonna attempt this in near future. If its okay I would bother you  time to time with doubts, questions and what notes. I have not been writing Rust for long and dont really have any serious insight for this crate, but I am gonna start with the pointers you gave and go through the code a bit and outline a flow for PKCS11 integration. For this I would bother you from time to time, is it okay with you?

**Comment by amrx101** [comment]
@ctz ,

I found this [1](https://github.com/arsing/openssl-pkcs11-demo) and this[2](https://github.com/mheese/rust-pkcs11). Can anyone of these help us in loading certs from HSM and supply to our repo, just wondering?

**Comment by ctz** [comment]
>  I hope commenting here is okay.

Yes please do.

> I found this 1 and this2.

I think the second of those looks most promising.

**Comment by amrx101** [comment]
@ctz , thanks for the reply man. 

This is what I am thinking of attempting.

First I will use the pkcs11 library from earlier comment and try to see if I can load and sign from my [HSM](https://github.com/MicrochipTech/cryptoauthlib). Once that is done I will leave that there.

I will then implement the `sign` and `signer` interface for HSM, where in the `signer` I will actually call the sign C method as we did in first step, if that is successful, then we will see how to go about creating a `ClientSession` or a `ServerSession`. 

I am still testing waters and will keep you posted. Thanks for the reply man. Please do let me know if you have any thing that I missed in my above 2 steps.

**Comment by amrx101** [comment]
@ctz ,

I did implemen the `signer` trait where I delegate the signing process to my `pkcs11engine`. I call it `PkcsSigner`. The `sign` method actually does a bunch of `C` calls to

1. Access the `PKCSEngine's` token .
2. Open a session using token from 1.
3. Call `C_Sign`
4. Close session.
5. Return signature.

Currently the `.so` file of the `PKCSEngine` is accessed in the `sign` method which should not be the case I am guessing. 

I am a bit stuck as to how do I integrate this `sign` implemented with an equivalent `ClientSession`(or a `ServerSession`) exposed by the library.

Do we create an `PkcsClientConfig(PkcsServerConfig)` that will have location of our `.so` file and slot and access pin etc?

I reckon if we provide a `PkcsCLientConfig` with parameters to access a `pkcs11engine`, should we create a new type of client ?

It would be helpful if you can provide some insight on this. Basically I don't have a clear flow as to what all changes would be required to have a server or a client that does look for certs on file system but the shared object file, access pin, slot etc provided by a pkcs11 engine? I am a bit lost in this part although I did implement the `sign`.

PS: Please do comment if some of my queries are not clear, as English is not my first language.

Thanks

**Comment by Ralith** [comment]
> Currently the .so file of the PKCSEngine is accessed in the sign method which should not be the case I am guessing.

A good approach is to have your library define a `Context` object which loads function pointers and manages the lifetime of the shared library through an internal `Arc`. The `Context` object could then have a public method to construct another type that implements `SigningKey` and internally contains a clone of that `Arc` through which it can access the function pointers and ensure the library remains loaded.

> I am a bit stuck as to how do I integrate this sign implemented with an equivalent ClientSession(or a ServerSession) exposed by the library.

It looks to me like `ClientConfig` is currently missing a way to specify a custom `SigningKey`. Most likely it should be modified to enable this.

**Comment by leonardodepaula** [comment]
Any news on this subject? @amrx101 , did you manage to find a solution?

**Comment by leonardodepaula** [comment]
For those looking for a solution, check this repository: https://github.com/leonardodepaula/Cryptoki-TLS
