### ISSUE TITLE
Bounded buffering

### ISSUE THREAD

**Issue by sp3d** [ctz/rustls#35]
The docs for .write() mention that prior to handshake completion a ClientSession or ServerSession will buffer data without bound.

This is arguably sane, though I would prefer an interface that only allows calling .write() after a handshake has been completed, to present uniform buffering semantics throughout the lifetime of the session.

However, I'm curious what buffering behavior is after initial handshaking, e.g. if an application repeatedly calls .write() but never .write_tls(). Does data still buffer indefinitely inside the Session, or does .write() stop accepting new bytes at some point if none leave the Session as TLS records?

If .write() buffers indefinitely during the "moving traffic" stage of a TLS connection, is there a way to detect how much data is currently buffered so applications can provide backpressure for writers that outpace the network?

There are analogous questions about the behavior of .read_tls()/.read().

Thanks!

**Comment by valarauca** [comment]
> However, I'm curious what buffering behavior is after initial handshaking, e.g. if an application repeatedly calls .write() but never .write_tls(). Does data still buffer indefinitely inside the Session, or does .write() stop accepting new bytes at some point if none leave the Session as TLS records?

Played around with the source code today a bit. The behaviour before/after handshake is identical. So you'll buffer unbounded internally.

**Comment by ctz** [comment]
Thanks for the bug. You're right in concluding that there is no working backpressure in the plaintext write direction. 5b96b9c relatedly introduced backpressure in the TLS read direction (for clients which look at `wants_read()` at least).

What shape of API would you find most useful? I can either expose the internal buffer state, or allow setting a limit on the buffer size and enforcing it by doing short writes.

**Comment by DemiMarie** [comment]
This seems like a memory consumption (DoS) security vulnerability in some scenarios, though I don't know of any.

**Comment by valarauca** [comment]
>This seems like a memory consumption (DoS) security vulnerability in some scenarios, though I don't know of any.

It is/isn't.

One does have unbound write access to a not yet completed handshake'd connection. This is a DoS as you _could_ exhaust the machine's memory. The problem is [_you are_ the server you are DoS'ing](https://ih1.redbubble.net/image.158316898.2338/flat,800x800,070,f.jpg), and there are many ways to accomplish this that are arguably simpler.

On the other hand, good software _should_ protect [you from yourself](http://img.ifcdn.com/images/71a4996922e040e9d7b4d2dfe84e586307e0d3ae7c6c3ba0ff5d65df906b3bc5_1.jpg).

A _reasonable_ limit might be 64KB. I suggest this because:

1. It is the default buffer size for Pipes in POSIX. So there is some historical context it isn't just a number out of left field.
2. Down the road a `splice`/`vmsplice`-esque system (Free/OpenBSD have different system call names) could handle the task of `VecBuf`, and de-fragmenting messages in kernel (adding `writev` support also) with zero copies. The Linux kernel (and *BSD kernel) dictate this be backed by pipes.
3. 64KB is still _huge_, so most reasonably use cases won't be effected. Yet malicious foolishness will still be capped.

**Comment by ctz** [comment]
1a1904ee4b18eda175551920f9a6e8e443176b46 is the first try at this.

**Comment by ctz** [comment]
Released in 0.6.0.
