### ISSUE TITLE
C-API

### ISSUE THREAD

**Issue by lu-zero** [ctz/rustls#360]
Would be possible to have a C-API in the future and/or is there interest in having it?

**Comment by Darkspirit** [comment]
There is https://github.com/mesalock-linux/mesalink. Would it be enough or do you mean an additional one?

**Comment by lu-zero** [comment]
The build system is quite complex, I was hoping for a non-openssl API that can be brought up using [cargo-c](https://github.com/lu-zero/cargo-c).

**Comment by Ben-Lichtman** [comment]
Could always use c-bindgen to wrap the rust in C clothes.

**Comment by lu-zero** [comment]
That's the idea, but is there a plan to sew those clothes? :)

**Comment by ctz** [comment]
I believe there's a downstream project starting soon to provide a C API for rustls. I'll update this issue when I know more.

**Comment by bdaehlie** [comment]
Internet Security Research Group (ISRG) is planning to start work soon on two projects that will integrate Rustls into C applications. The first one is described here:

https://www.abetterinternet.org/post/memory-safe-curl/

We are planning to create a C API for Rustls. We do not want to use Mesalink since it uses the OpenSSL API, which has too many issues.

When we create this C API, would you be willing to merge it into Rustls or would we need to work downstream? I believe there is a lot of value to be had in incrementally replacing less safe TLS components of C applications with Rustls, and ideally that API would be part of Rustls itself.

**Comment by ctz** [comment]
Yeah I think it makes sense for it to be a subcrate in this repo, since it'll live a similar life to the base crate.

**Comment by ctz** [comment]
-> https://github.com/abetterinternet/crustls
