### ISSUE TITLE
is there a Dummy's guide on how to use rustls with letsencrypt?

### ISSUE THREAD

**Issue by gitmko0** [ctz/rustls#364]
Please provide a dummy's guide on this. It'll be invaluable to all. Thanks in advance.

Basically using letsencrypt cert on rustls. Best if comes with docker instance, else it's fine.

**Comment by amrx101** [comment]
What is special about`letsencrypt` certs that they warrant their own examples?

The flow is simple, suppose you are a `Client`  then you

- create `ClientConfig` with appropriate `root_chain`, `client_certificate` and `keys`.

The [docs](https://docs.rs/rustls/0.17.0/rustls/) are pretty straight forward.

**Comment by gotheer** [comment]
tlsserver and tlsclient are full worked examples. These both use mio.
Please where I can find these examples. Thank you.

**Comment by amrx101** [comment]
@gotheer , here you [go](https://github.com/ctz/rustls/tree/master/rustls-mio/examples).

**Comment by ctz** [comment]
> Please where I can find these examples. Thank you.

They live here in the repo: https://github.com/ctz/rustls/tree/master/rustls-mio/examples

I'm going to close this since it's a little outside the scope of this crate; with that said:

- There are several acme client crates that exist.
- If someone wants to look into making an openssl-free acme client crate then I'd love to have a rustls example that depends upon it for demonstrating the ALPN proof method: I'd suggest looking at and building upon https://github.com/est31/rcgen as a first step.
