### ISSUE TITLE
CloseNotify alert received when using rustls/examples/simpleclient.rs

### ISSUE THREAD

**Issue by volfco** [ctz/rustls#380]
I'm trying to figure out how to write my own HTTP client using `rustls/examples/simpleclient.rs` as a base. 

The code in master works when using it against `google.com:443` or oracle.com, but fails on other popular sites such as reddit.com, twitter.com, github.com with the following error (this was against twitter.com):

```
Current ciphersuite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: ConnectionAborted, error: "CloseNotify alert received" }', src/main.rs:40:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Not sure where in the pipeline this error is happening.

**Comment by ctz** [comment]
This is a normal and expected error: I've ensure it's mentioned in the docs as of a5e14882. TLDR: it signifies clean connection closure by the peer. close_notify does not have universal support in TLS libraries/applications, so that's why you see variance between hosts. In your application you should respond by tearing down the underlying TCP connection.

**Comment by volfco** [comment]
I opened this to fix the example code so it's handled cleanly. I'm just trying to wrap my head around all of this, which is why I called out the example.
