### ISSUE TITLE
Question on close_notify

### ISSUE THREAD

**Issue by zethra** [ctz/rustls#419]
Hello,

When a connection is closed does rustls send close_notify automatically?

**Comment by ctz** [comment]
No. Because rustls doesn't do IO for itself, it doesn't know when the connection is closed. If you get a half-close at the TCP level and want to shut the other direction, call https://docs.rs/rustls/0.18.1/rustls/trait.Session.html#tymethod.send_close_notify followed by https://docs.rs/rustls/0.18.1/rustls/trait.Session.html#tymethod.write_tls.
