### ISSUE TITLE
X448 / Ed448 / Ed25519 support

### ISSUE THREAD

**Issue by Darkspirit** [ctz/rustls#52]
X448 is a perfect replacement for secp521r1 to gain "level 8" security here: https://www.keylength.com/en/3/

[RFC8080: Edwards-Curve Digital Security Algorithm (EdDSA) for DNSSEC](https://tools.ietf.org/html/rfc8080)

[btls](https://gitlab.com/ilari_l/btls) has both, but no TLS 1.3.

**Comment by briansmith** [comment]
*ring* supports Ed25519 and webpki supported Ed25519 certificates.

Note that https://tools.ietf.org/html/rfc8422 says:

>   All EdDSA computations MUST be performed according to [RFC8032] or
   its successors.  Data to be signed/verified is run through the EdDSA
   algorithm with no hashing (EdDSA will internally run the data through
   the "prehash" function PH).  The context parameter for Ed448 MUST be
   set to the empty string.

I believe that Rustls already has to do things in a way that would automatically work for Ed25519 since *ring* exposes an API that reflects what RFC8422 requires implementations to do. So, perhaps we just need to wire up the key loading and add some tests?

**Comment by briansmith** [comment]
Also, Go implements this as of Go 1.13 (See https://go-review.googlesource.com/c/go/+/177698/4//COMMIT_MSG), so we should be able to do interop testing against Go even if BoringSSL and BoGo haven't been updated for Ed25519 yet.

**Comment by ctz** [comment]
I'm going to close this since ed25519 is now supported. x448 and ed448 are for another day.
