### ISSUE TITLE
BorrowMessage

### ISSUE THREAD

**Issue by manuels** [ctz/rustls#54]
While implementing DTLS I came accross `BorrowMessage`. What purpose does it have?
Is there a reason why not to simply pass a `&Message`?

**Comment by ctz** [comment]
The difference between `Message` and `BorrowMessage` is that `Message` owns its memory, while `BorrowMessage` borrows its memory from an external slice.

The purpose is optimising the application data send path. That path starts with an `io::Write` where you get a borrow to a byte slice. Putting this into a `Message` would involve copying the whole thing, which is inefficient. So that gets put into a `BorrowMessage`, which is then [fragmented](https://github.com/ctz/rustls/blob/master/src/msgs/fragmenter.rs#L50) into more `BorrowMessage`s which are [individually](https://github.com/ctz/rustls/blob/master/src/session.rs#L430) [encrypted](https://github.com/ctz/rustls/blob/master/src/session.rs#L327). Because these slices are immutable (they belong to the caller of rustls) encrypting them necessarily involves allocating memory: so the result of encrypting them is a `Message`.

**Comment by manuels** [comment]
Oh, I see. I just saw the uses of `Message::to_borrow(&self) -> BorrowMessage`. These could in fact be replaced by `&Message`, right? But I totally missed the other uses of `BorrowMessage`!
