### ISSUE TITLE
Should we restrict configuration options for cipher suites?

### ISSUE THREAD

**Issue by djc** [ctz/rustls#549]
There was a discussion in the crustls repo where some Google folks are pretty adamant that we should restrict configuration options for cipher suites: https://github.com/abetterinternet/crustls/issues/58.

**Comment by briansmith** [comment]
I don't understand what this issue is about. Could you clarify it in a way that doesn't require reading the crustls issue?

**Comment by djc** [comment]
I think they're basically arguing we should not allow users to select which cipher suites can be supported.

**Comment by briansmith** [comment]
If Rustls ever hopes to be used within a web browser, then it would likely need to sometimes support cipher suites that most users shouldn't use, because web browsers are very conservative about disabling bad things. And the web browser usually/always has knobs to control these at a pretty fine-grained level. So having only one cipher suite configuration would basically disqualify Rustls from being used in a web browser, unless it forced all its users to match exactly what web browsers do.

If Rustls hopes to be used in embedded use cases then it needs the ability the disable cipher suites in a way where the code for supporting those cipher suites isn't linked into the final executable. That's why the cipher suite configuration has the shape it currently has. The same with the webpki project; the API is the way it is, and why the *ring* API is the way it is.

**Comment by icing** [comment]
Note: the discussion on crustls also applies to do away with cipher *ordering* in clients/servers.

**Comment by djc** [comment]
Upon further reflection, it seems to me that rustls is opinionated in which cipher suites (and early on, which protocol versions) it supports/exposes, and therefore fixating the exact cipher suite configuration (both selection and order) doesn't feel as important. If we decide that a cipher suite should no longer be supported, then we'll remove it from the API. Because our selection is more opinionated, the ability to configure clients/servers based on it is okay. I especially find the embedded use case convincing, since selecting just one of the available suites seems a fine solution for projects where code size matters.

**Comment by ctz** [comment]
I would like to improve the defaults for rustls in the future, so that architectures we know have poor AES-GCM performance will automatically prefer chacha20poly1305 suites. But I think that's best done here, in one place, rather than in every consumer of rustls.

Separately to that, the configuration surface to configure ciphersuites isn't really something I'd expect 99% of consumers to touch; originally it was there (in just the second or third commit) to support exercise of each suite separately; predating any real testing effort. But now there are other reasons for it, valuable but IMO still very niche.

**Comment by sayrer** [comment]
> Right now rustls defaults to offering all cipher suites that it supports. Configurability lets users (a) change the preference order of cipher suites and (b) disable cipher suites.

This has come up in implementing QUIC and ECH as well, where TLS 1.2 and cipher suites that accompany it need to be banned. An all-or-nothing approach seems unlikely to work to me, but I do think the Rustls server should default to TLS 1.3 only, and require a crate feature to enable 1.2.

**Comment by Ralith** [comment]
> This has come up in implementing QUIC and ECH as well, where TLS 1.2 and cipher suites that accompany it need to be banned

My experience implementing QUIC on rustls is that restricting the protocol versions in the configuration to 1.3 Just Works.

**Comment by icing** [comment]
@Ralith you mean for QUIC, right? My MacOS Big Sur native `curl` command from Apple does not speak TLSv1.3.

**Comment by djc** [comment]
I think @Ralith means that, if you just set the config `versions` to only contain `TLSv1_3`, the code will do the right thing with respect to the cipher suites allowed. Starting new QUIC sessions currently panics if any version other than 1.3 is in `config.versions`.

**Comment by briansmith** [comment]
> Starting new QUIC sessions currently panics if any version other than 1.3 is in `config.versions`.

That's a bug, isn't it?

**Comment by briansmith** [comment]
> My experience implementing QUIC on rustls is that restricting the protocol versions in the configuration to 1.3 Just Works.

If you don't use the constructor that takes a list of cipher suites, then aren't all the cipher suites linked into the executable, even though most won't be used?

**Comment by Ralith** [comment]
> That's a bug, isn't it?

No, QUIC specifically mandates TLS 1.3.

**Comment by briansmith** [comment]
I know that QUIC mandates TLS 1.3. The panic is definitely a bug.

**Comment by briansmith** [comment]
I feel like this should be closed. In both the old and new/upcoming configuration interface we have an easy path that picks good defaults, and the "I need something special" path which is important for less typical users. I don't see us removing the latter interface.

**Comment by djc** [comment]
I agree.
