### ISSUE TITLE
Code coverage is completely broken

### ISSUE THREAD

**Issue by djc** [ctz/rustls#551]
See for example here: https://github.com/ctz/rustls/pull/550/checks?check_run_id=2080872821. The last successful run appears to be from 13 days ago, in https://github.com/ctz/rustls/actions/runs/600956417.

@ctz I usually use tarpaulin for this. Any particular reason for using lcov instead?

**Comment by briansmith** [comment]
*ring* has code coverage based on the new source-based code coverage in Rust nightly that has worked pretty well so far. I use
`RING_COVERAGE=1 mk/cargo.sh +${{ matrix.rust_channel }} test -vv --target=${{ matrix.target }} ${{ matrix.cargo_options }} ${{ matrix.features }} ${{ matrix.mode }}` where `mk/cargo.sh` is https://github.com/briansmith/ring/blob/main/mk/cargo.sh. It requires llvm-11 to be installed.

> @ctz I usually use tarpaulin for this.

FWIW, I didn't use that because that only works on x86_64 according to its docs and it requires an extra cargo subcommand to be installed. I prefer the source-based coverage.

**Comment by ctz** [comment]
> @ctz I usually use tarpaulin for this. Any particular reason for using lcov instead?

lcov is just used for post-processing the output, the actual coverage measurement is done with the llvm coverage plugin. Previously to that kcov was used (similar in function to tarpaulin -- based on ptrace) but coverage tests took around an hour -- not sure if tarpaulin is better than that.

The hazard here is that when rustc nightly change their llvm major version, we need to track it. An alternative could be pinning a specific nightly?

**Comment by djc** [comment]
We could just add a some code to extract the LLVM version from `rustc -vV` to check if it matches the version of LLVM installed for the coverage job, and throw a more specific error if it doesn't?

**Comment by ctz** [comment]
That would definitely be a good improvement, yeah. In the meantime I've fixed the immediate problem in #553

**Comment by djc** [comment]
Yay, thanks!

**Comment by djc** [comment]
With the immediate issue solved in #553 and diagnostics improved in #557, let's close this.
