### ISSUE TITLE
Make TLS 1.2 a crate feature

### ISSUE THREAD

**Issue by sayrer** [ctz/rustls#633]
I think it's time to start separating TLS 1.2 as a crate feature (initially default-on).

**Comment by briansmith** [comment]
I would suggest that as part of the next round of API changes, we change the API to make it so the user has to explicitly choose whether to enable TLS 1.2 or not. From here we can then try to optimize the way the TLS 1.2 code is (not) referenced unnecessarily so that the link-time dead code elimination throws away TLS 1.2 code when it isn't enabled.

I also suggest we move all the TLS 1.2-specific code out of the shared modules and into TLS-1.2-specific submodules.

Is it important for you that this be done using feature flags? My experience with feature flags has lead me to really dislike maintaining them unless they are really necessary.

**Comment by sayrer** [comment]
> Is it important for you that this be done using feature flags? My experience with feature flags has lead me to really dislike maintaining them unless they are really necessary.

I agree feature flags are unpleasant, but I do like the assurance that the crate just won't compile / work if something tries to use the code that's trying to be avoided. Perhaps there are some approaches here that don't require a perfect partition, and would result in a failed negotiation, rather than having all TLS 1.2 omitted from the compiled binary.

**Comment by briansmith** [comment]
> I agree feature flags are unpleasant, but I do like the assurance that the crate just won't compile / work if something tries to use the code that's trying to be avoided.

Well, kinda. However, often it has the opposite effect: One expects some code will be omitted, but it gets included because another crate in the application's dependencies enabled the feature. For example, within Rustls already I find the `"quic" feature confusing because the code guarded by `#[cfg(feature = "quic")]` might get executed even when Rustls is being used by a crate that doesn't enable the "quic" feature.

**Comment by sayrer** [comment]
I see your point, although I don't really use Cargo outside of demo code for this and a host of other reasons.

Maybe the API should change at the public boundary, and a crate feature would be required to do something like `use rustls::ConnectionAllowsTls12`;

**Comment by sayrer** [comment]
> I would suggest that as part of the next round of API changes, we change the API to make it so the user has to explicitly choose whether to enable TLS 1.2 or not.

Sorry to belabor the point if this what you meant: make all of the backward-compatible API calls use TLS 1.3 only, and only allow TLS 1.2 if you change the method/function/struct names and enable the crate feature to make those visible. I know this is harsh, but I think it is the right approach.

**Comment by djc** [comment]
We could make that part of the builder API, I suppose.

**Comment by djc** [comment]
For this, we should maybe also change the version set as part of the config types to an enum that only has 1.2 and 1.3 variants (maybe `SupportedProtocolVersion`?). The current setup where we use the IANA enumeration that includes TLS 1.0 etc seems suboptimal.

**Comment by djc** [comment]
Implemented in #740.

**Comment by sayrer** [comment]
Thank you!
