### ISSUE TITLE
Shared RootCertStore

### ISSUE THREAD

**Issue by icing** [ctz/rustls#688]
For client authentication in http servers I'd like to load a `RootCertStore` only once and use that in all `ServerConfigs` where it is needed. It seems to me that I'd need a variant of `AllowAnyAuthenticatedClient` that keeps an `Arc<RootCertStore>` as member.

Trying to implement my own verified for the trait, there are several internal utility functions I would need to copy, and the `SUPPORTED_SIG_ALGS` as well. That seems fairly unattractive.

Have I overlooked something or wouldn't it be suitable for rustls to offer such a trait implementation?

**Comment by jsha** [comment]
Some additional context (copied from #704):

ClientConfig and ServerConfig both say: "Making one of these can be expensive, and should be once per process rather than once per connection." What we're finding in the curl and Apache work is that making just one ClientConfig or ServerConfig per process is not practical.

For curl, the curl API allows different TLS settings on a per-connection basis. So you might have one request that uses one group of settings, and another request that uses a different group of settings.

For Apache, we can't choose a CertifiedKey to respond with until after we've seen the ClientHello. The Acceptor API in #89 will solve part of that problem, and we're working around in the meantime. But in either case we wind up constructing a fresh ServerConfig for each connection.

I believe the expensive part of building a ServerConfig or a ClientConfig is primarily loading the RootCertStore. Is that right? If so, it makes sense to make RootCertStores shareable with an Arc, allowing ServerConfig and ClientConfig to be cheap to build.

**Comment by djc** [comment]
Are you aware that on main neither `ClientConfig` nor `ServerConfig` contain a `RootCertStore` directly? So you can already provide a `ClientCertVerifier`/`ServerCertVerifier` that uses an `Arc` internally to reference the `RootCertStore`. I'm still not convinced that this is common enough that it's something rustls should provide directly.

**Comment by jsha** [comment]
That's good to know about `ClientConfig` on main no longer having a direct `RootCertStore`. I think that solves the problem adequately on the client side.

**Comment by djc** [comment]
This seems to be addressed in the current API.
