### ISSUE TITLE
MTU minimums

### ISSUE THREAD

**Issue by sayrer** [ctz/rustls#701]
In #697, I noticed that the minimum MTU (6 bytes) is probably too small. A reasonable minimum is 68 (RFC 791). If QUIC is supported, it should be 1280.

Adding a ClientConfig method to return one of these values would be nice, but I think more builder or type-level separation of features like TLS 1.2 / TLS 1.3 / QUIC / ECH would be needed first.

**Comment by ctz** [comment]
I am currently overhauling this.

- first, MTU was the wrong terminology. It'd be more correct if it were MSS, but then that only makes sense for TCP.
- second `ClientConfig::set_mtu` is the wrong place for error handling, as the `mtu` field is `pub`. That means `config.set_mtu(Some(50))` and `config.mtu = Some(50)` mean different things; that's extremely confusing.
- third, `ClientConfig::set_mtu` doesn't have a `ServerConfig` version
- fourth, there's also a maximum that we should apply here too, otherwise we'll fail interop

**Comment by sayrer** [comment]
Sounds good. In that case, maybe the minimum should be 32-34.

68
- 20 (IP header)
- 20 (TCP header)
- 12 (room for IPSec etc)

That's still way smaller than I've ever seen, but maybe embedded cases do this. At least this number avoids the payload getting close to zero.

**Comment by sayrer** [comment]
Oh, I see you already patched this to 32 bytes. nm
