### ISSUE TITLE
loosen up width settings in .rustfmt.toml?

### ISSUE THREAD

**Issue by sayrer** [ctz/rustls#702]
Chain width was set to 40 intentionally. This limit seems really aggressive, to the point that it encourages overly concise names. I think many of these widths might be better at 80 or so.

I don't feel strongly about this issue (it's just formatting), but I wondered what others think. Maybe the tradeoff is different using a tiling window manager?

Here's an example of one that I just hit.

![Screen Shot 2021-05-15 at 2 07 57 PM](https://user-images.githubusercontent.com/253473/118378248-49e6b180-b587-11eb-9fe8-acb7a22f89f8.png)

**Comment by djc** [comment]
I'd be happy to have it a little wider too, though I guess it might not help in this specific example?

**Comment by sayrer** [comment]
> I'd be happy to have it a little wider too, though I guess it might not help in this specific example?

It still gets reformatted at 60, but not 80.

**Comment by ctz** [comment]
40 is an attempt to make all but the tiniest chains split vertically over several lines, as I find this much more readable. If we were to move to 60, an example of poorer readability for me would be:

```diff
-    let mut cipher_suites: Vec<_> = config
-        .cipher_suites
-        .iter()
-        .map(|cs| cs.suite)
-        .collect();
+    let mut cipher_suites: Vec<_> = config.cipher_suites.iter().map(|cs| cs.suite).collect();
```

Ideally this parameter would be by path length rather than horizontal space (at which point I'd like paths of 4 or more elements split horizontally, allowing `self.member.function(args)` to exist on one line), but that's not where we are with the tooling.
