### ISSUE TITLE
wants_read() returns true on new ClientSession

### ISSUE THREAD

**Issue by icing** [ctz/rustls#733]
In rustls/src/client/mod.rs line 445, the client session wants to read before the handshake has started. However, in the TLS protocol, there is never anything to read before the client sent the initial hello.

**Comment by jsha** [comment]
(Permalink to line 445 in v/0.19.0: https://github.com/ctz/rustls/blob/v/0.19.0/rustls/src/client/mod.rs#L445)

BTW a somewhat related thing: a Connection will say it `wants_read` even after it has received a close_notify. One could say it should stop returning true from `wants_read` after that - although on the other hand it might be useful from the TcpStream perspective to read again in order to observe the TCP close.

**Comment by icing** [comment]
> (Permalink to line 445 in v/0.19.0: https://github.com/ctz/rustls/blob/v/0.19.0/rustls/src/client/mod.rs#L445)
> 
> BTW a somewhat related thing: a Connection will say it `wants_read` even after it has received a close_notify. One could say it should stop returning true from `wants_read` after that - although on the other hand it might be useful from the TcpStream perspective to read again in order to observe the TCP close.

Servers need to cleanup reads and linger that for all connections anyway. But otherwise I agree with you. `rustls` should be just concerned with the TLS protocol state of things. And it should not indicate a read wish if the protocol state does not allow incoming data for the session, imo.
